octagon: update bsp
commit 9b4693d
Author: WanWizard <wanwizard@openpli.org>
Date:   Mon Nov 4 17:07:27 2024 +0000

    fix libjpeg version collision

    ERROR: octagon-libs-sx86v2-20221203-r1 do_packagedata: Recipe octagon-libs-sx88v2 is trying to install files into a shared area when those files already exist. The files and the manifests listing them are:
        /openpli/oe/scarthgap/build/tmp/pkgdata/sx88v2/runtime-reverse/libjpeg-dbg
            (matched in manifest-sx88v2-libjpeg-turbo.packagedata)
        /openpli/oe/scarthgap/build/tmp/pkgdata/sx88v2/runtime-reverse/libjpeg-dev
            (matched in manifest-sx88v2-libjpeg-turbo.packagedata)

    and

    Exception: FileNotFoundError: [Errno 2] No such file or directory: '/openpli/oe/scarthgap/build/tmp/pkgdata/sx88v2/runtime-reverse/libjpeg-dbg' -> '/openpli/oe/scarthgap/build/tmp/work/sx88v2-oe-linux-gnueabi/direct>