nodejs: Update to 22.11.0
Fix compile error (Ubuntu 24.10):

ext.o.d.raw -isystem/home/hains/openpli-oe-core/build/tmp/work/x86_64-linux/nodejs-native/20.12.2/recipe-sysroot-native/usr/include -
/openpli-oe-core/build/tmp/work/x86_64-linux/nodejs-native/20.12.2/recipe-sysroot-native/usr/include -O2 -pipe -c
| Illegal instruction (core dumped)
| make[1]: *** [libnode.target.mk:13: Release/obj/gen/node_javascript.cc] Error 132

Drop obselete 'mix-mips-build' patch as support support for Mipsel has been removed with V8.

|                  from ../deps/v8/src/libplatform/tracing/trace-buffer.h:11,
|                  from ../deps/v8/src/libplatform/tracing/trace-buffer.cc:5:
| ../deps/v8/include/v8config.h:813:2: error: #error "Host architecture was not detected as supported by v8"
|   813 | #error "Host architecture was not detected as supported by v8"
|       |  ^~~~~

See e.g.
https://github.com/nxhack/openwrt-node-packages/issues/464

Nopejs-native does still build for Mipsel.
Although, a proper working seems doubtful?